# Generated by Django 4.2.21 on 2026-06-10 22:59

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_superuser_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('so', 'Somali')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_certificates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_course_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.profile_photo_upload_path),
        ),
    ]
