# Generated by Django 4.2.21 on 2026-06-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default='Hilaac Academy', max_length=200)),
                ('tagline', models.CharField(default='Baro Xirfado Casri ah, Dhis Mustaqbalkaaga', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, max_length=300)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('footer_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
