# Generated by Django 4.2.21 on 2026-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_mvp_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_created_6f786c_idx',
            old_name='core_auditl_created_module_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_ro_087e07_idx',
            old_name='core_auditl_user_role_created_idx',
        ),
    ]
