# Generated by Django 4.2.21 on 2026-06-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated search keywords', max_length=500),
        ),
    ]
