# Generated by Django 4.2.21 on 2026-06-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_level_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video directly (recommended). Used before video URL if both are set.', null=True, upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or paste a video URL (YouTube, Vimeo, Cloudinary, etc.) if not uploading a file.'),
        ),
    ]
