# Generated by Django 4.2.21 on 2026-06-01 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_lesson_video_file_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
