# Generated by Django 4.2.21 on 2026-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_level_instructor_level_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Video preview thumbnail. Auto-captured from the video or upload your own.', null=True, upload_to='lessons/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='level',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Course cover image. Recommended 1280x720 (JPG, PNG or WEBP).', null=True, upload_to='courses/covers/'),
        ),
    ]
