# Generated by Django 4.2.21 on 2026-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_thumbnail_alter_level_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='banner',
            field=models.ImageField(blank=True, help_text='Optional wide banner image shown on the course page.', null=True, upload_to='courses/banners/'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_tag',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='level',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short tagline shown under the title', max_length=200),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(help_text='Course title, e.g. English Beginner', max_length=100),
        ),
    ]
