# Generated by Django 4.2.21 on 2026-06-01 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_level_banner_level_level_tag_level_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Free preview: visible to everyone before enrollment.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview_views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='level',
            name='certificate_included',
            field=models.BooleanField(default=True, help_text="Show 'Certificate included' on the course page"),
        ),
        migrations.AddField(
            model_name='level',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='One objective per line'),
        ),
        migrations.AddField(
            model_name='level',
            name='requirements',
            field=models.TextField(blank=True, help_text='Course requirements, one per line'),
        ),
        migrations.AddField(
            model_name='level',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills students acquire, one per line'),
        ),
        migrations.AddField(
            model_name='level',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Who this course is for, one per line'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'level')},
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars')),
                ('comment', models.TextField(blank=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('level', 'student')},
            },
        ),
    ]
