# Generated by Django 4.2.21 on 2026-06-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_is_preview_lesson_preview_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='lessons/resources/')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('pptx', 'Presentation'), ('audio', 'Audio'), ('zip', 'ZIP Archive'), ('other', 'Other')], default='pdf', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
