# Generated by Django 4.2.21 on 2026-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessonresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Short lesson summary shown to students.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Lesson notes, instructions, or reading text.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Free preview: only the first lesson in the course may be marked (max 1).'),
        ),
    ]
