# Generated by Django 4.2.21 on 2026-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_fields_and_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_message',
            field=models.CharField(blank=True, help_text='Message shown to student after push', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Provider receipt / transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Legacy / internal reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('completed', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'level', 'status'], name='payments_pa_student_a8fdc3_idx'),
        ),
    ]
