# Generated by Django 4.2.21 on 2026-06-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partner_schools/')),
                ('website_url', models.URLField(blank=True, help_text='Opens in a new tab when the logo is clicked.')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner School',
                'verbose_name_plural': 'Partner Schools',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
