# Generated by Django 4.2.21 on 2026-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_partner_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional short label for admin lists.', max_length=200)),
                ('message', models.CharField(help_text='Text shown in the scrolling ticker.', max_length=500)),
                ('announcement_type', models.CharField(choices=[('discount', 'Course Discount'), ('new_course', 'New Course Launch'), ('registration', 'Registration Notice'), ('scholarship', 'Scholarship'), ('system', 'System Announcement'), ('welcome_somali', 'Somali Welcome Message')], default='system', max_length=30)),
                ('background_color', models.CharField(default='#1E4D8F', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('link_url', models.URLField(blank=True, help_text='Optional — makes the announcement clickable.')),
                ('start_date', models.DateTimeField(blank=True, help_text='Leave blank to show immediately.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
