# Generated by Django 4.2.21 on 2026-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntroductionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='How Hilaac Academy Works', max_length=200)),
                ('title_somali', models.CharField(default='Sida Loo Isticmaalo Hilaac Academy', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional extended description shown in the admin panel.')),
                ('video_file', models.FileField(help_text='MP4 or WebM recommended.', upload_to='platform_videos/')),
                ('thumbnail', models.ImageField(help_text='Cover image shown before play.', upload_to='platform_thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(default=0, editable=False, help_text='Set automatically when possible; used for completion analytics.')),
                ('is_active', models.BooleanField(default=True)),
                ('impression_count', models.PositiveIntegerField(default=0, editable=False)),
                ('play_count', models.PositiveIntegerField(default=0, editable=False)),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0, editable=False)),
                ('completion_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Platform Introduction Video',
                'verbose_name_plural': 'Platform Introduction Videos',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
