# Generated by Django 4.2.21 on 2026-06-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_legalpage_somali'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintroductionvideo',
            name='description_somali',
            field=models.TextField(blank=True, help_text='Somali description for the admin panel.'),
        ),
        migrations.AddField(
            model_name='platformintroductionvideo',
            name='english_play_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='platformintroductionvideo',
            name='somali_play_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='platformintroductionvideo',
            name='thumbnail_somali',
            field=models.ImageField(blank=True, help_text='Somali video cover image (optional).', upload_to='platform_thumbnails/'),
        ),
        migrations.AddField(
            model_name='platformintroductionvideo',
            name='video_file_somali',
            field=models.FileField(blank=True, help_text='Somali guide — optional second language video.', upload_to='platform_videos/'),
        ),
        migrations.AlterField(
            model_name='platformintroductionvideo',
            name='description',
            field=models.TextField(blank=True, help_text='English description for the admin panel.'),
        ),
        migrations.AlterField(
            model_name='platformintroductionvideo',
            name='thumbnail',
            field=models.ImageField(help_text='English video cover image shown before play.', upload_to='platform_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='platformintroductionvideo',
            name='title_somali',
            field=models.CharField(default='Sida Hilaac Academy u Shaqeyso', max_length=200),
        ),
        migrations.AlterField(
            model_name='platformintroductionvideo',
            name='video_file',
            field=models.FileField(help_text='English guide — MP4 or WebM recommended.', upload_to='platform_videos/'),
        ),
    ]
